# Site settings
title: Ezra Huynh
email: thuah@uci.edu
description: A designer
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "ezraozaki.github.io" # the base hostname & protocol for your site
twitter_username: whoknowimhere
github_username:  ezraozaki

# Build settings
markdown: kramdown
permalink: pretty
