# Site settings
title: Ezra Huynh
email: thuah@uci.edu
description: > # this means to ignore newlines until "baseurl:"
  A designer, a lifelong learner and a rain lover
baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
