# Site settings
title: Hello World! 
email: thuah@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  A UX/UI designer driven by usability and aesthetics
baseurl: "" # the subpath of your site, e.g. /blog
url: "ezraozaki.github.io" # the base hostname & protocol for your site
github_username:  ezraozaki
exclude: [vendor]
# Build settings
markdown: kramdown
permalink: pretty
