# Site settings
title: 
email: thuah@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a UX/UI designer driven by usability and aesthetics. To me, design is like cooking, a dish can taste really good but still does not look good. And as a designer/cook, I am striving to achieve both.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ezraozaki.github.io" # the base hostname & protocol for your site
github_username:  ezraozaki
exclude: [vendor]
# Build settings
markdown: kramdown
permalink: pretty
